l_english:
 production_decisions:0 "Production Decisions"
 militaryproduction:0 "Military Production Boost"
 navalproduction:0 "Naval Production Boost"
 construction:0 "Construction Boost"
 upgradeequipment:0 "Equipment Upgrade Boost"
 industryrepair:0 "Industry Repair Boost"